name: Server CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint-fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: server
      run: npm install

    - name: Run ESLint with autofix
      working-directory: server
      run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: client
      run: npm install

    - name: Run linting
      working-directory: server
      run: npm run lint

    - name: Build for production
      working-directory: server
      run: npm run build
